apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldap-pv1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem·
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ldap-storage
  local:
    path: /vagrant/ldap_pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s1.nogada.dev
          - k8s2.nogada.dev
          - k8s3.nogada.dev
