apiVersion: v1
kind: Service
metadata:
  name: node-js-deploy
  namespace: himang10
  labels:
    name: node-js-deploy
spec:
  type: LoadBalancer
  ports:
  - port: 80
  sessionAffinity: ClientIP
  selector:
    name: node-js-deploy
