apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-many
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv-many
  hostPath:
    path: /vagrant/dir_test
